# Generated by Django 5.1 on 2024-08-17 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prayer_title', models.CharField(max_length=200)),
                ('prayer_content', models.TextField()),
                ('prayer_pdf_urls', models.JSONField(blank=True, null=True)),
                ('prayer_youtube_urls', models.JSONField(blank=True, null=True)),
                ('view', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
