# Generated by Django 5.1 on 2024-08-17 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prayer',
            name='img_url',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
